[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pydocstyle]
convention = "numpy"
add-ignore = ['D102', 'D402']

[tool.pydoclint]
style = 'numpy'
check-arg-order = false
require-return-section-when-returning-nothing = false
quiet = true
